version: "3.7"
networks:
    net1:
        driver: overlay
    
services:

    service_1:
        image: amranlab/service_1
        ports:
            - "5000:5000"
        networks:
            - net1
        deploy:
            replicas: 2
        

    service_2:
        image: amranlab/service_2
        networks:
            - net1
        deploy:
            replicas: 2
        

    service_3:
        image: amranlab/service_3
        networks:
            - net1
        deploy:
            replicas: 3

    service_4:
        image: amranlab/service_4
        networks:
            - net1
        deploy:
            replicas: 3
        



